### ISSUE TITLE
Unphysical boundary effects in sandwich tdvp time evolution

### ISSUE THREAD

**Issue by HumpyBlumpy** [amilsted/evoMPS#27]
Hi,
Thanks for making this code available!

I tried running the `heisenberg_af_sandwich_scattering.py` file from the example folder.
I find that there are strong unphysical effects at the boundaries of the nonuniform region, as can be seen in the plot.
These begin to occur right from the beginning of time evolution, before any disturbance had enough time to propagate to the edge, so I think this definitely should not happen.
I also tried the impurity hamiltonian from `heisenberg_af_sandwich_impurity.py` by changing the time evolution to a complex time step, and I see similar unphysical boundary effects.

Thanks

[heisn_af_sandwich_scat.pdf](https://github.com/amilsted/evoMPS/files/8151182/heisn_af_sandwich_scat.pdf)

**Comment by amilsted** [comment]
Thanks for the report! I have been using the sandwich MPS code recently for another project (albeit, not using the `go()` function - see [this code](https://github.com/FuTen/qollider1D)), so I don't think there's a fundamental problem here. I will try to reproduce this when I get a chance. Possibly these are integration errors that would be reduced by taking smaller time steps, but it does look a little suspicious.

**Comment by HumpyBlumpy** [comment]
Ok I will try to play around with the time step and report back.
By the way, the link you shared leads to a 404 error.

**Comment by amilsted** [comment]
Ah, thanks. Corrected the link. Should have pointed to [this](https://github.com/amilsted/kollider1D).

**Comment by HumpyBlumpy** [comment]
I tried running the script with dt = 0.005 (instead of 0.01) and I dont really see an improvement. This seems to me already a very small dt and going smaller may not be practical I guess.

**Comment by amilsted** [comment]
Okay, I did a little testing. The boundary effects occur even without the local quench (application of ops in the centre). They are present because the bulk state is actually not the ground state with the current repo version of the `heisenberg_af_uniform.py`! Setting `load_saved_ground = True` in the script will fix the problem. I will make that change to help avoid confusion in the future.
